### ISSUE TITLE
pycocotools.COCO couldn't be loaded

### ISSUE THREAD

**Issue by zhengthomastang** [open-mmlab/mmskeleton#414]
I followed through the steps in [GETTING_STARTED.md](https://github.com/open-mmlab/mmskeleton/blob/master/doc/GETTING_STARTED.md) to set up in conda. All the requirements were installed successfully. However, when verifying mmskeleton and mmdetection using `python mmskl.py pose_demo [--gpus $GPUS]`, I encountered the following error: 

```
(mmskeleton) thtang@thtang-X299-A:~/Code/mmskeleton$ python mmskl.py pose_demo
/home/thtang/anaconda3/envs/mmskeleton/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py:41: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
  "Cython.Distutils.old_build_ext does not properly handle dependencies "
Traceback (most recent call last):
  File "mmskl.py", line 7, in <module>
    import mmskeleton
  File "/home/thtang/Code/mmskeleton/mmskeleton/__init__.py", line 1, in <module>
    from . import utils
  File "/home/thtang/Code/mmskeleton/mmskeleton/utils/__init__.py", line 3, in <module>
    from .checkpoint import load_checkpoint, get_mmskeleton_url, cache_checkpoint
  File "/home/thtang/Code/mmskeleton/mmskeleton/utils/checkpoint.py", line 1, in <module>
    from mmcv.runner import load_checkpoint as mmcv_load_checkpoint
  File "/home/thtang/anaconda3/envs/mmskeleton/lib/python3.7/site-packages/mmcv-1.3.5-py3.7.egg/mmcv/runner/__init__.py", line 3, in <module>
    from .base_runner import BaseRunner
  File "/home/thtang/anaconda3/envs/mmskeleton/lib/python3.7/site-packages/mmcv-1.3.5-py3.7.egg/mmcv/runner/base_runner.py", line 12, in <module>
    from ..parallel import is_module_wrapper
  File "/home/thtang/anaconda3/envs/mmskeleton/lib/python3.7/site-packages/mmcv-1.3.5-py3.7.egg/mmcv/parallel/__init__.py", line 6, in <module>
    from .registry import MODULE_WRAPPERS
  File "/home/thtang/anaconda3/envs/mmskeleton/lib/python3.7/site-packages/mmcv-1.3.5-py3.7.egg/mmcv/parallel/registry.py", line 5, in <module>
    MODULE_WRAPPERS = Registry('module wrapper')
  File "/home/thtang/anaconda3/envs/mmskeleton/lib/python3.7/site-packages/mmcv-1.3.5-py3.7.egg/mmcv/utils/registry.py", line 90, in __init__
    self._scope = self.infer_scope() if scope is None else scope
  File "/home/thtang/anaconda3/envs/mmskeleton/lib/python3.7/site-packages/mmcv-1.3.5-py3.7.egg/mmcv/utils/registry.py", line 142, in infer_scope
    filename = inspect.getmodule(inspect.stack()[2][0]).__name__
  File "/home/thtang/anaconda3/envs/mmskeleton/lib/python3.7/inspect.py", line 1513, in stack
    return getouterframes(sys._getframe(1), context)
  File "/home/thtang/anaconda3/envs/mmskeleton/lib/python3.7/inspect.py", line 1490, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "/home/thtang/anaconda3/envs/mmskeleton/lib/python3.7/inspect.py", line 1464, in getframeinfo
    lines, lnum = findsource(frame)
  File "/home/thtang/anaconda3/envs/mmskeleton/lib/python3.7/inspect.py", line 780, in findsource
    module = getmodule(object, file)
  File "/home/thtang/anaconda3/envs/mmskeleton/lib/python3.7/inspect.py", line 733, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "/home/thtang/anaconda3/envs/mmskeleton/lib/python3.7/site-packages/lazy_import-0.2.2-py3.7.egg/lazy_import/__init__.py", line 156, in __getattribute__
    _load_module(self)
  File "/home/thtang/anaconda3/envs/mmskeleton/lib/python3.7/site-packages/lazy_import-0.2.2-py3.7.egg/lazy_import/__init__.py", line 537, in _load_module
    msg.format(**modclass._lazy_import_error_strings)), None)
  File "<string>", line 3, in raise_from
ImportError: mmskeleton.utils.third_party attempted to use a functionality that requires module pycocotools.COCO, but it couldn't be loaded. Please install pycocotools and retry.
```

I have tried installing pycocotools using options [here](https://github.com/matterport/Mask_RCNN/issues/6), but the same error still occurred.

**Comment by zhengthomastang** [comment]
Found the error. Need to correct this line in [coco.py](https://github.com/open-mmlab/mmskeleton/blob/master/mmskeleton/datasets/coco.py#L21): 

```
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval
```

Also need to correct these in [third_party.py](https://github.com/open-mmlab/mmskeleton/blob/master/mmskeleton/utils/third_party.py#L4-L5): 

```
COCO = lazy_import.lazy_module("pycocotools.coco.COCO")
COCOeval = lazy_import.lazy_module("pycocotools.cocoeval.COCOeval")
```

**Comment by Donny2333** [comment]
Maybe you could have a try to install mmcv==0.4.3

**Comment by zhengthomastang** [comment]
@Donny2333 Thanks. My problem has been resolved. This ticket can be closed.

**Comment by ArFuchs** [comment]
Hi, I still have the same Issue as OP. I Tried everything I could find concerning this issue, but I keep getting this error. Any help is really appreciated.

**Comment by heduo-star** [comment]
> @Donny2333 Thanks. My problem has been resolved. This ticket can be closed.

@zhengthomastang Hello, can you tell me how did you resolve it?

**Comment by zouchao8527** [comment]
> @zhengthomastang Hello, could you tell me where is third_party.py?I can't retrieve it in the project file.Thanks!
